version: "3.7"

services:
  wordpress:
    image: wordpress
    restart: always
    ports:
      - 3100:80
    environment:
      WORDPRESS_DB_HOST: mysql
      WORDPRESS_DB_NAME: wordpress_test
      WORDPRESS_DB_PASSWORD: example
      ABSPATH: /usr/src/wordpress/
      WORDPRESS_DEBUG: 1
      WORDPRESS_CONFIG_EXTRA: |
        define( 'SCRIPT_DEBUG', true );
    volumes:
      - wordpress_data:/var/www/html
  cli:
    image: wordpress:cli
    restart: always
    user: xfs
    environment:
      WORDPRESS_DB_HOST: mysql
      WORDPRESS_DB_NAME: wordpress_test
      WORDPRESS_DB_PASSWORD: example
      ABSPATH: /usr/src/wordpress/
      WORDPRESS_DEBUG: 1
      WORDPRESS_CONFIG_EXTRA: |
        define( 'SCRIPT_DEBUG', true );
    volumes:
      - wordpress_data:/var/www/html
      - ./wp:/var/www/html/wp
    depends_on:
      - mysql
      - wordpress
  mysql:
    image: mysql:5.7
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: example
      MYSQL_DATABASE: wordpress_test
    volumes:
      - ./wp/sql:/docker-entrypoint-initdb.d
  # phpmyadmin
  phpmyadmin:
    depends_on:
      - mysql
    image: phpmyadmin/phpmyadmin
    restart: always
    ports:
      - "3101:80"
    environment:
      PMA_HOST: mysql
      MYSQL_ROOT_PASSWORD: example

volumes:
  wordpress_data:
